development:
  adapter: postgresql
  encoding: unicode
  database: hellorails_db
  pool: 5
  username: postgres
  password: Duque
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: hellorails_db
  pool: 5
  username: postgres
  password: Duque
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: hellorails_db
  pool: 5
  username: postgres
  password: Duque
  host: localhost